# Generated by Django 3.2.9 on 2021-12-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='users',
        ),
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.CharField(default='admin@hivecorelimited.com', max_length=250),
            preserve_default=False,
        ),
    ]
