# Generated by Django 3.2.9 on 2021-12-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211201_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_CREATED', 'Leave Created'), ('LEAVE_REJECTED', 'Leave Rjected'), ('LEAVE_NEW', 'Leave New'), ('LEAVE_PENDING', 'Leave Pending')], max_length=500),
        ),
    ]
